<!-- IS NULL Operator:

The IS NULL operator is used to check if a column's value is NULL.

Syntax:
SELECT column1, column2, ...
FROM table_name
WHERE column_name IS NULL;


Example: Retrieve rows where the "email" column is NULL.
SELECT first_name, last_name
FROM customers
WHERE email IS NULL;







IS NOT NULL Operator:

The IS NOT NULL operator is used to check if a column's value is not NULL.

Syntax:
SELECT column1, column2, ...
FROM table_name
WHERE column_name IS NOT NULL;


Example: Retrieve rows where the "phone" column is not NULL.
SELECT first_name, last_name
FROM customers
WHERE phone IS NOT NULL; -->
